/**
 * Centralized asset path constants for public/ directory images.
 * All paths are absolute URLs served from the public folder.
 *
 * Naming convention:
 * - kebab-case for file names
 * - Semantic prefix: card-, bg-, hero-, analysis-, workflow-
 * - Directory grouping: /images/{category}/filename
 */

export const ASSETS = {
  hero: {
    video: '/images/hero/hero-bg-video.mp4',
    cell1: '/images/hero/hero-cell-1.mp4',
    cell2: '/images/hero/hero-cell-2.mp4',
  },
  backgrounds: {
    academic: '/images/backgrounds/bg-academic-section.jpg',
    omics: '/images/backgrounds/bg-omics-section.jpg',
    services: '/images/backgrounds/bg-services-section.jpg',
  },
  cards: {
    genomics: '/images/cards/card-bg-genomics.jpg',
    transcriptomics: '/images/cards/card-bg-transcriptomics.jpg',
    proteomics: '/images/cards/card-bg-proteomics.jpg',
    metabolomics: '/images/cards/card-bg-metabolomics.jpg',
    singlecell: '/images/cards/card-bg-singlecell.jpg',
    methylation: '/images/cards/card-bg-methylation.jpg',
    metagenome: '/images/cards/card-bg-metagenome.jpg',
    chipseq: '/images/cards/card-bg-chipseq.jpg',
    gwas: '/images/cards/card-bg-gwas.jpg',
    rnaseq: '/images/cards/card-bg-rnaseq.jpg',
    machineLearning: '/images/cards/card-bg-machine-learning.jpg',
    systemsBiology: '/images/cards/card-bg-systems-biology.jpg',
    multiomicsCorrelation: '/images/cards/card-bg-multiomics-correlation.jpg',
    editing: '/images/cards/card-bg-editing.jpg',
    academicFund: '/images/cards/card-bg-academic-fund.jpg',
    academicPaper: '/images/cards/card-bg-academic-paper.jpg',
    academicPatent: '/images/cards/card-bg-academic-patent.jpg',
    academicReport: '/images/cards/card-bg-academic-report.jpg',
    fund: '/images/cards/card-bg-fund.jpg',
    patent: '/images/cards/card-bg-patent.jpg',
    sciPaper: '/images/cards/card-bg-sci-paper.jpg',
  },
  analysis: {
    genomicsVariant: '/images/analysis/analysis-genomics-variant.jpg',
    genomicsCnv: '/images/analysis/analysis-genomics-cnv.jpg',
    rnaExpression: '/images/analysis/analysis-rna-expression.jpg',
    rnaSplicing: '/images/analysis/analysis-rna-splicing.jpg',
    proteinMs: '/images/analysis/analysis-protein-ms.jpg',
    proteinPtm: '/images/analysis/analysis-protein-ptm.jpg',
    metabolite: '/images/analysis/analysis-metabolite.jpg',
    metabolismPathway: '/images/analysis/analysis-metabolism-pathway.jpg',
  },
  omics: {
    genomics: '/images/omics/genomics.jpg',
    transcriptomics: '/images/omics/transcriptomics.jpg',
    proteomics: '/images/omics/proteomics.jpg',
    metabolomics: '/images/omics/metabolomics.jpg',
  },
  workflow: {
    genomics: '/images/workflow/workflow-genomics.png',
    transcriptomics: '/images/workflow/workflow-transcriptomics.png',
    proteomics: '/images/workflow/workflow-proteomics.png',
    metabolomics: '/images/workflow/workflow-metabolomics.png',
    heroGenomics: '/images/workflow/workflow-hero-genomics.jpg',
    heroTranscriptomics: '/images/workflow/workflow-hero-transcriptomics.jpg',
    heroProteomics: '/images/workflow/workflow-hero-proteomics.jpg',
    heroMetabolomics: '/images/workflow/workflow-hero-metabolomics.jpg',
  },
  charts: {
    alignment: '/images/charts/alignment.png',
    area: '/images/charts/area.png',
    atacseq: '/images/charts/atacseq.png',
    bar: '/images/charts/bar.png',
    boxplot: '/images/charts/boxplot.png',
    bubble: '/images/charts/bubble.png',
    cnv: '/images/charts/cnv.png',
    correlation: '/images/charts/correlation.png',
    dendrogram: '/images/charts/dendrogram.png',
    errorbar: '/images/charts/errorbar.png',
    fusion: '/images/charts/fusion.png',
    goBubble: '/images/charts/go-bubble.png',
    gsea: '/images/charts/gsea.png',
    heatmap: '/images/charts/heatmap.png',
    ideogram: '/images/charts/ideogram.png',
    keggPathway: '/images/charts/kegg-pathway.png',
    kmeans: '/images/charts/kmeans.png',
    line: '/images/charts/line.png',
    manhattan: '/images/charts/manhattan.png',
    methylation: '/images/charts/methylation.png',
    network: '/images/charts/network.png',
    oncoplot: '/images/charts/oncoplot.png',
    pca: '/images/charts/pca.png',
    phylogenetic: '/images/charts/phylogenetic.png',
    pie: '/images/charts/pie.png',
    qqplot: '/images/charts/qqplot.png',
    radar: '/images/charts/radar.png',
    roc: '/images/charts/roc.png',
    sankey: '/images/charts/sankey.png',
    scatter: '/images/charts/scatter.png',
    splicing: '/images/charts/splicing.png',
    stackedBar: '/images/charts/stackedbar.png',
    sunburst: '/images/charts/sunburst.png',
    survival: '/images/charts/survival.png',
    umap: '/images/charts/umap.png',
    venn: '/images/charts/venn.png',
    violin: '/images/charts/violin.png',
    volcano: '/images/charts/volcano.png',
    waterfall: '/images/charts/waterfall.png',
    wgcna: '/images/charts/wgcna.png',
  },
  workflowSteps: {
    genomicsStep1: '/images/workflow-steps/genomics-step1.png',
    genomicsStep2: '/images/workflow-steps/genomics-step2.png',
    genomicsStep3: '/images/workflow-steps/genomics-step3.png',
    genomicsStep4: '/images/workflow-steps/genomics-step4.png',
    genomicsStep5: '/images/workflow-steps/genomics-step5.png',
    genomicsStep6: '/images/workflow-steps/genomics-step6.png',
    transcriptomicsStep1: '/images/workflow-steps/transcriptomics-step1.png',
    transcriptomicsStep2: '/images/workflow-steps/transcriptomics-step2.png',
    transcriptomicsStep3: '/images/workflow-steps/transcriptomics-step3.png',
    transcriptomicsStep4: '/images/workflow-steps/transcriptomics-step4.png',
    transcriptomicsStep5: '/images/workflow-steps/transcriptomics-step5.png',
    transcriptomicsStep6: '/images/workflow-steps/transcriptomics-step6.png',
    proteomicsStep1: '/images/workflow-steps/proteomics-step1.png',
    proteomicsStep2: '/images/workflow-steps/proteomics-step2.png',
    proteomicsStep3: '/images/workflow-steps/proteomics-step3.png',
    proteomicsStep4: '/images/workflow-steps/proteomics-step4.png',
    proteomicsStep5: '/images/workflow-steps/proteomics-step5.png',
    proteomicsStep6: '/images/workflow-steps/proteomics-step6.png',
    metabolomicsStep1: '/images/workflow-steps/metabolomics-step1.png',
    metabolomicsStep2: '/images/workflow-steps/metabolomics-step2.png',
    metabolomicsStep3: '/images/workflow-steps/metabolomics-step3.png',
    metabolomicsStep4: '/images/workflow-steps/metabolomics-step4.png',
    metabolomicsStep5: '/images/workflow-steps/metabolomics-step5.png',
    metabolomicsStep6: '/images/workflow-steps/metabolomics-step6.png',
  },
} as const;
